version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8002'
    ports:
      - 8002:8002
    volumes:
      - .:/app
    depends_on:
      - db

  
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: vista
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
volumes:
  db:
    driver: local